### ISSUE TITLE
Option to detect duplicate values

### ISSUE THREAD

**Issue by hugovk** [legoktm/jsonchecker#5]
I think both of these are technically valid JSON:

```json
{
    "a" : [
      "x",
      "x"
    ]
}
```

```json
{
    "a" : [
      "x",
      "y",
      "x"
    ]
}
```

But, like with duplicate keys, there are many places where it's unwanted.

Would it be possible to add an option to detect duplicate values?

**Comment by jayvdb** [comment]
Resolved with ea605f9d8. Thanks for pushing through so many good fixes.

**Comment by hugovk** [comment]
:+1: And thanks both for the original tool!

Time for a new release soon?

**Comment by jayvdb** [comment]
Definitely time for a new release.  See #12 as preparation for it.
